// Common 5-letter words for OhMyWordle
pub const WORDS: &[&str] = &[
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
    "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
    "alike", "align", "alive", "alley", "allow", "alone", "along", "alter",
    "angel", "anger", "angle", "angry", "ankle", "annex", "antic", "anvil",
    "aorta", "apple", "apply", "arena", "argue", "arise", "armor", "aroma",
    "arose", "array", "arrow", "arson", "artsy", "aside", "asset", "atlas",
    "atone", "attic", "audio", "audit", "aunts", "avail", "avert", "avoid",
    "award", "aware", "awful", "axial", "azure", "badge", "baker", "basic",
    "basis", "batch", "bayou", "beach", "beard", "beast", "began", "begin",
    "being", "belle", "bench", "bevel", "bible", "biome", "birch", "birth",
    "bison", "black", "blade", "blame", "bland", "blank", "blast", "blaze",
    "bleat", "bleed", "blend", "bless", "blind", "bliss", "bloat", "block",
    "blood", "bloom", "blown", "blues", "blunt", "blurb", "blurt", "blush",
    "board", "boast", "bonus", "boost", "booth", "bound", "boxer", "brace",
    "braid", "brain", "brake", "brand", "brave", "bravo", "brawl", "bread",
    "break", "breed", "bribe", "bride", "brief", "brine", "bring", "brink",
    "brisk", "brood", "brook", "broom", "broth", "brown", "brows", "brunt",
    "brush", "brute", "build", "built", "bulge", "bully", "burns", "burst",
    "cabal", "cabin", "cable", "camel", "candy", "cargo", "carol", "carry",
    "carve", "catch", "cause", "cease", "cedar", "chain", "chair", "chalk",
    "chaos", "charm", "chart", "chase", "cheap", "check", "cheek", "cheer",
    "chess", "chest", "chief", "chili", "chill", "china", "choir", "chord",
    "cinch", "civic", "civil", "claim", "clamp", "clank", "clash", "clasp",
    "class", "cleat", "clerk", "click", "cliff", "climb", "cling", "cloak",
    "clock", "clone", "close", "cloth", "cloud", "clown", "cluck", "clump",
    "coach", "coast", "cobra", "coins", "color", "comet", "comic", "comma",
    "coral", "could", "count", "court", "cover", "covet", "craft", "crane",
    "crash", "creak", "cream", "creek", "creep", "crest", "crimp", "crisp",
    "cross", "crowd", "crown", "crude", "cruel", "crush", "crust", "curly",
    "cycle", "daddy", "daily", "dairy", "dance", "daunt", "debug", "debut",
    "decay", "decoy", "delay", "delta", "depot", "depth", "derby", "devil",
    "disco", "ditch", "dodge", "dogma", "doing", "doubt", "dough", "dowdy",
    "dowel", "draft", "drain", "drama", "drape", "drawl", "drawn", "dread",
    "dream", "drift", "drink", "drool", "drove", "drown", "drums",
    "dryer", "duchy", "dully", "dummy", "dunce", "dwarf", "dwell", "dying",
    "eager", "eagle", "early", "earth", "eight", "elder", "elect", "elfin",
    "elite", "email", "ember", "empty", "ended", "enjoy", "enter", "envoy",
    "equip", "error", "essay", "ethic", "evade", "event", "every", "exact",
    "excel", "exile", "extra", "fable", "faced", "faint", "fairy", "faith",
    "false", "fancy", "farce", "fatal", "fault", "fawns", "feast", "feign",
    "femur", "fence", "ferry", "fetch", "fewer", "fiber", "field", "fiend",
    "fiery", "final", "flair", "flame", "flank", "flare", "flash", "flask",
    "flaws", "flesh", "float", "flood", "floor", "floss", "flour", "flout",
    "flown", "flush", "focal", "foray", "force", "forge", "forum", "foyer",
    "frail", "frame", "frank", "fraud", "fresh", "front", "frost", "froth",
    "froze", "fruit", "fully", "funny", "gable", "games", "gauze", "gavel", "girth", "given", "gland", "glare", "glass", "gleam",
    "glide", "glint", "gloat", "globe", "gloom", "gloss", "glove", "glyph",
    "gnome", "going", "grace", "grade", "grain", "grand", "grant", "graph",
    "grasp", "grass", "grate", "grave", "graze", "greed", "greet", "grief",
    "grill", "grime", "grind", "groan", "groin", "groom", "grope", "gross",
    "group", "grove", "growl", "grown", "gruel", "gruff", "grump", "guard",
    "guile", "guise", "gusto", "halve", "harsh", "haven", "heart", "heavy",
    "hedge", "heist", "hence", "heron", "hinge", "hippo", "hoist", "honey",
    "honor", "horde", "hover", "human", "humid", "humor", "hurry", "hyena",
    "ideal", "igloo", "image", "imply", "inbox", "infer", "inlet", "inner",
    "input", "inter", "intro", "inure", "issue", "ivory", "japan", "joust",
    "judge", "juice", "juicy", "jumbo", "karma", "kayak", "knack", "kneel",
    "knelt", "knife", "knoll", "known", "label", "lance", "large", "laser",
    "latch", "later", "lathe", "leapt", "learn", "lease", "leash",
    "leave", "legal", "lemon", "level", "light", "linen", "lingo", "liver",
    "local", "lofty", "login", "loner", "loose", "lowly", "lucid", "lucky",
    "lusty", "lyric", "magic", "maize", "maker", "manor", "march", "marry",
    "mayor", "media", "mercy", "merit", "metal", "miles", "mimic", "mirth",
    "miser", "moist", "molar", "money", "month", "moral", "motor", "mound",
    "mourn", "mouth", "moved", "mulch", "music", "nasal", "naval", "nerve",
    "nicer", "night", "ninja", "noble", "noise", "north", "notch", "novel",
    "nymph", "occur", "ocean", "offer", "often", "onset", "opera", "optic",
    "orbit", "order", "other", "ought", "outer", "ounce", "ovary", "ozone",
    "paint", "panda", "panic", "panel", "paper", "party", "pasta", "patch",
    "pause", "peace", "pearl", "pedal", "penny", "perch", "petal", "phage",
    "phase", "phone", "photo", "piano", "pilot", "pinch", "pixel",
    "pizza", "place", "plain", "plaid", "plank", "plant", "plate", "plaza",
    "plead", "pluck", "plume", "plump", "plunk", "plush", "poach",
    "point", "poker", "polar", "polka", "power", "press", "price", "prick",
    "prime", "prism", "privy", "probe", "prong", "proof", "prose", "proud",
    "prove", "prowl", "pulse", "punch", "pupil", "puppy", "purse", "pygmy",
    "query", "quest", "queue", "quick", "quiet", "quota", "quote", "rabbi",
    "radar", "radix", "radon", "raise", "rally", "ranch", "range", "rapid",
    "raven", "reach", "ready", "realm", "rebel", "rebus", "recap", "reign",
    "relax", "reply", "repel", "repot", "rerun", "reuse", "ridge", "right",
    "risky", "rival", "rivet", "roast", "robin", "robot", "rocky", "round",
    "route", "royal", "rugby", "ruler", "rusty", "safer", "saint", "salsa",
    "satin", "sauce", "savor", "savvy", "scald", "scalp", "scant", "scare",
    "scene", "scent", "scone", "scoop", "score", "scorn", "scout", "scram",
    "screw", "seize", "sense", "serve", "seven", "sever", "shade", "shake",
    "shame", "shape", "share", "sharp", "shave", "shawl", "shelf", "shell",
    "shift", "shine", "shock", "shore", "short", "shout", "shrew", "skill",
    "skimp", "skulk", "skull", "skunk", "slain", "slant", "slash", "sleep",
    "sleek", "slept", "slice", "slide", "slime", "sling", "slink", "slosh",
    "sloth", "slump", "slunk", "slyly", "smart", "smash", "smear", "smell",
    "smile", "smirk", "smoke", "snail", "snake", "snare", "sneak", "snout",
    "solar", "solve", "sorry", "south", "space", "spare", "spark", "spasm",
    "spawn", "speak", "spear", "speed", "spell", "spend", "spill", "spite",
    "split", "spoil", "spoke", "spook", "spoon", "sport", "spout",
    "spree", "squad", "squat", "squid", "stack", "staff", "stage", "stain",
    "stake", "stale", "stamp", "stand", "stare", "stark", "start", "stash",
    "state", "stays", "steam", "steel", "steep", "steer", "stern", "stiff",
    "sting", "stock", "stomp", "stone", "stool", "store", "storm", "story",
    "strap", "straw", "stray", "strut", "stuck", "study", "stuff", "stump",
    "stung", "stunk", "stunt", "suave", "sugar", "suite", "sunny", "super",
    "surge", "swamp", "swear", "sweat", "sweep", "sweet", "swept", "swift",
    "swirl", "swoop", "sword", "swore", "sworn", "swung", "taboo", "talon",
    "tapir", "taunt", "tawny", "teach", "tense", "tepid", "thief", "thing",
    "think", "third", "thorn", "those", "three", "threw", "throw", "thrum",
    "thumb", "thump", "tiger", "tight", "timer", "tipsy", "titan", "today",
    "token", "topaz", "torch", "total", "touch", "tough", "towel", "tower",
    "toxic", "trace", "track", "trade", "trail", "train", "trait", "trawl",
    "treat", "trend", "trial", "tribe", "trice", "trick", "troop", "trout",
    "trove", "truce", "truck", "truly", "trump", "trunk", "truss", "trust",
    "truth", "tulip", "tumor", "tuner", "twang", "tweak", "twill", "twirl",
    "udder", "ulcer", "ultra", "uncut", "under", "unfit", "union",
    "unite", "until", "unzip", "upper", "upset", "urban", "usage", "usual",
    "utter", "vague", "value", "valve", "vapor", "vault", "vaunt", "verge",
    "verse", "vicar", "vigor", "viola", "viral", "virus", "visor", "vista",
    "vital", "vixen", "vodka", "voice", "voter", "vouch", "vulva",
    "wager", "waltz", "warty", "waste", "watch", "water", "weary", "weave",
    "wedge", "weedy", "weigh", "weird", "whale", "wheat", "wheel", "where",
    "which", "while", "whiff", "whine", "white", "whole", "whose", "wider",
    "wield", "windy", "witch", "woman", "women", "world", "wormy", "worst",
    "would", "wound", "wrath", "wring", "wrist", "wrote", "yacht", "yearn",
    "yeast", "yield", "young", "yours", "youth", "zebra", "zesty", "zippy",
    "zones",
];

/// Filter to only valid 5-letter words
pub fn valid_words() -> Vec<&'static str> {
    WORDS.iter().copied().filter(|w| w.len() == 5).collect()
}

/// Check if a word is in the valid word list (5-letter words only)
pub fn is_valid_word(word: &str) -> bool {
    let lower = word.to_lowercase();
    WORDS.iter().any(|&w| w.len() == 5 && w == lower)
}
